services:
  client:
    env_file:
      - ./client/.env.docker
    build:
      context: ./client
    ports:
      - "5555:80"
    depends_on:
      - server
    networks:
      - internal

  server:
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:./data.db
    build:
      context: ./server
    volumes:
      - ./server:/app
    command: sh -c "yarn install && npx prisma generate && yarn db:push && yarn start"
    networks:
      - internal

networks:
  internal:
    driver: bridge
